name: Build for arm

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            make build-full
      - name: Upload release image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
        with:
          name: Release image
          path: dist/main